ReiseBuro.Web/Controllers/ReservationsController.cs
using System;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ReiseBuro.Entities.Models;
using ReiseBuro.Web.Authentication;
using ReiseBuro.Repository.IRepository;
using ReiseBuro.Web.Helper;

namespace ReiseBuro.Web.Controllers
{
    [ReiseAuthorize(Roles = "Administrator,Kullanici")]
    public class ReservationsController : Controller
    {
        private readonly IReservationRepository _resRepositroy;
        private readonly ICurrencyRepository _currencyRepository;
        private readonly IUserActionRepository _userActionRepository;
        private readonly IUserRepository _userRepository;
        private readonly ICountryRepository _countryRepository;

        private readonly static string WaitingState = System.Configuration.ConfigurationManager.AppSettings["Waiting"].ToString();
        private readonly static string ConfirmState = System.Configuration.ConfigurationManager.AppSettings["Confirm"].ToString();
        private readonly static string CancelState = System.Configuration.ConfigurationManager.AppSettings["Cancel"].ToString();
        private readonly static string InsideState = System.Configuration.ConfigurationManager.AppSettings["Inside"].ToString();
        private readonly static string TempConfirmState = System.Configuration.ConfigurationManager.AppSettings["TempConfirm"].ToString();

        public ReservationsController(IReservationRepository resRepository, ICurrencyRepository currencyRepository, IUserActionRepository userActionRepository, IUserRepository userRepository, ICountryRepository countryRepository)
        {
            this._resRepositroy = resRepository;
            this._currencyRepository = currencyRepository;
            this._userActionRepository = userActionRepository;
            this._userRepository = userRepository;
            this._countryRepository = countryRepository;
        }


        // GET: Reservations
        public ActionResult Index()
        {
            ViewBag.Currencies = _currencyRepository.GetAll();
            var actions = _userActionRepository.GetAll();
            ViewBag.Waiting = WaitingState;
            ViewBag.Users = _userRepository.GetAll();
            ViewBag.Confirm1 = TempConfirmState;

            if (UserInfoHelper.UserRole() == "Administrator")
            {
                ViewBag.actions = actions;

                return View(_resRepositroy.GetAll());

            }
            else
            {
                ViewBag.actions = actions.Where(f => f.UserId == UserInfoHelper.GetUserid());
                return View(_resRepositroy.GetAll().Where(i => i.UserId == UserInfoHelper.GetUserid()));

            }
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.currency = _currencyRepository.GetAll();
            Reservation reservation = _resRepositroy.Get(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }

            if (UserInfoHelper.UserRole() != "Administrator")
            {
                if (UserInfoHelper.GetUserid() != reservation.UserId)
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            ViewBag.DeservedAmount = _userActionRepository.GetAll().FirstOrDefault(f => f.ResId == reservation.Id).DeservedAmount;
            return View(reservation);
        }

        // GET: Reservations/Create
        public ActionResult Create()
        {
            var user = (User)Session["user"];
            var country = _countryRepository.GetByCountryCode(user.CountryCode);
            var currency = _currencyRepository.Get(country.CurrencyId);
            ViewBag.currencyId = currency.Id;
            ViewBag.currencyName = currency.Name;
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VoucherNo,CheckIn,CheckOut,Name,Surname,Birthday,Agenta,ExtraBed,GuestNote,CurrencyId,Person")] Reservation reservation)
        {
            var user = (User)Session["user"];
            long newResId = 0;
            if (ModelState.IsValid)
            {
                try
                {
                    reservation.BookingDate = DateTime.Now;
                    reservation.UserId = UserInfoHelper.GetUserid();
                    newResId = _resRepositroy.Insert(reservation);
                }
                catch (Exception ex)
                {
                    TempData["error"] = "Rezervasyon kaydedilemedi. ";
                    return RedirectToAction("Index");
                }
                try
                {
                    var validCampaign = CampaignsHelper.GetBonusAmount(reservation);

                    decimal FinalBonus = validCampaign.Bonus;
                    if (user.BoundUser != null)
                    {
                        FinalBonus = FinalBonus / 2;
                        var masterAction = new UserAction
                        {
                            BalanceDue = 0,
                            BalanceReceivable = 0,
                            DeservedAmount = FinalBonus,
                            ActionDate = DateTime.Now,
                            ResId = Convert.ToInt32(newResId),
                            UserId = Convert.ToInt32(user.BoundUser),
                            ActionState = WaitingState

                        };
                        _userActionRepository.Insert(masterAction);
                    }

                    var action = new UserAction
                    {
                        BalanceDue = 0,
                        BalanceReceivable = 0,
                        DeservedAmount = FinalBonus,
                        ActionDate = DateTime.Now,
                        ResId = Convert.ToInt32(newResId),
                        UserId = reservation.UserId,
                        ActionState = WaitingState
                    };

                    _userActionRepository.Insert(action);
                }

                catch (Exception ex)
                {
                    TempData["error"] = "Rezervasyon kaydedildi ama kampanya bulunamadı. Lütfen yönetici ile iletişime geçiniz. ";
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = Resources.Resource.zorunluAlan;
            }

            var country = _countryRepository.GetByCountryCode(user.CountryCode);
            var currency = _currencyRepository.Get(country.CurrencyId);
            ViewBag.currencyId = currency.Id;
            ViewBag.currencyName = currency.Name;
            ViewBag.CurrencyList = SelectListItemHelper.CurrencyList(user.CountryCode);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = _resRepositroy.Get(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            var resConfirme = _userActionRepository.GetAllByResId(id);
            if (resConfirme.Any(f => f.ActionState == ConfirmState) || resConfirme.Any(i => i.ActionState == InsideState))
            {
                TempData["error"] = Resources.Resource.rezEditHataMesaj1;//Confirme veya Inside durumundaki rezervasyonu düzenleyemezsiniz.

                return RedirectToAction("Index");
            }

            if (reservation.UserId != UserInfoHelper.GetUserid() && UserInfoHelper.UserRole() == "Kullanici")
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            var user = (User)Session["user"];
            ViewBag.StateList = SelectListItemHelper.StateKeyValue();
            ViewBag.Currency = _currencyRepository.Get(reservation.CurrencyId).Xml;
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Reservation reservation)//[Bind(Include = "Id,UserId,VoucherNo,CheckIn,CheckOut,Name,Surname,Birthday,Agenta,GuestNote,Amount,CurrencyId")]
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _resRepositroy.Update(reservation);
                    var validCampaign = CampaignsHelper.GetBonusAmount(reservation);

                    var resuser = _userRepository.Get(reservation.UserId);
                    if (resuser.BoundUser != null)
                    {
                        validCampaign.Bonus = validCampaign.Bonus / 2;
                    }

                    var allActions = _userActionRepository.GetAllByResId(reservation.Id);//.FirstOrDefault(f => f.ActionState == WaitingState);
                    foreach (var currentAction in allActions)
                    {
                        if (currentAction.ActionState == TempConfirmState)
                        {
                            currentAction.ActionState = WaitingState;
                        }

                        currentAction.ActionDate = DateTime.Now;

ReiseBuro.Web/Views/Reservations/Create.cshtml
@model ReiseBuro.Entities.Models.Reservation
@using ReiseBuro.Web.Resources

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var currencyId = ViewBag.currencyId;
    var currencyName = ViewBag.currencyName;

    var lang = System.Globalization.CultureInfo.CurrentCulture.TwoLetterISOLanguageName;
}

<input type="hidden" id="culture" value="@lang" />
<div class="block-header">
    <h2>@Resource.rezolustur</h2>
</div>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                <h4 class="error-message">@TempData["error"]</h4>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row clearfix">

                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.VoucherNo, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.VoucherNo, new { htmlAttributes = new { @class = "form-control" } })

                                    @Html.ValidationMessageFor(model => model.VoucherNo, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.CheckIn, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.CheckIn, new { htmlAttributes = new { @class = "datepicker form-control" } })

                                    @Html.ValidationMessageFor(model => model.CheckIn, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.CheckOut, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.CheckOut, new { htmlAttributes = new { @class = "datepicker form-control" } })

                                    @Html.ValidationMessageFor(model => model.CheckOut, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-label" })
                                <span>@ReiseBuro.Entities.Resources.Resource.isimRuscaAciklama</span>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "form-label" })
                                <span>@ReiseBuro.Entities.Resources.Resource.soyisimRuscaAciklama</span>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })

                                    @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.Label(Resource.dogumTarihGunAyYil, htmlAttributes: new { @class = "form-label" })
                                <span>@Resource.dogumTarihGAY</span>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Agenta, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Agenta, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Agenta, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.GuestNote, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.GuestNote, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.GuestNote, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-sm-12">
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Person, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.TextBoxFor(model => model.Person, new { @class = "form-control" })                                  
                                    @Html.ValidationMessageFor(model => model.Person, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" value=@currencyId name="CurrencyId" />

                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" value="@Resource.rezkaydet" class="btn bg-teal btn-lg waves-effect" />
                        </div>
                    </div>

                }

            </div>
        </div>
    </div>
</div>


@section Styles{

}

@section Scripts{
      <!-- Autosize Plugin Js -->
<script src="~/assets/plugins/autosize/autosize.js"></script>
<script src="~/assets/plugins/jquery-inputmask/jquery.inputmask.bundle.js"></script>
    <script>
        var lang = $('#culture').val();

        if (lang == 'tr') {
            $('#CheckIn').bootstrapMaterialDatePicker({ time: false, format: 'DD.MM.YYYY', locale: 'tr', lang: 'tr', language: 'tr', cancelText: 'İptal', clearButton: true, minDate: new Date() });
            $('#CheckOut').bootstrapMaterialDatePicker({ time: false, format: 'DD.MM.YYYY', locale: 'tr', lang: 'tr', language: 'tr', cancelText: 'İptal', clearButton: true, minDate: new Date() });
        }
        else if (lang == 'de') {
            $('#CheckIn').bootstrapMaterialDatePicker({ time: false, format: 'DD.MM.YYYY', locale: 'de', lang: 'de', language: 'de', cancelText: 'İptal', clearButton: true, minDate: new Date() });
            $('#CheckOut').bootstrapMaterialDatePicker({ time: false, format: 'DD.MM.YYYY', locale: 'de', lang: 'de', language: 'de', cancelText: 'İptal', clearButton: true, minDate: new Date() });
        }

        else {

            $('#CheckIn').bootstrapMaterialDatePicker({ time: false, format: 'DD.MM.YYYY', locale: 'en', lang: 'en', language: 'en', cancelText: 'İptal', clearButton: true, minDate: new Date() });
            $('#CheckOut').bootstrapMaterialDatePicker({ time: false, format: 'DD.MM.YYYY', locale: 'en', lang: 'en', language: 'en', cancelText: 'İptal', clearButton: true, minDate: new Date() });
        }
      
        $('#Birthday').inputmask('dd.mm.yyyy', { placeholder: '__/__/____' });
        $(document).ready(function () {


            $('#CheckIn').change(function (e) {          
                $('#CheckOut').bootstrapMaterialDatePicker('setMinDate', $('#CheckIn').val());
            });

            $('#CheckOut').change(function (e) {
                $('#CheckIn').bootstrapMaterialDatePicker('setMaxDate', $('#CheckOut').val());
            });
        
        });
   
      
    </script>

}

ReiseBuro.Web/Views/Reservations/Delete.cshtml
@model ReiseBuro.Entities.Models.Reservation
@using ReiseBuro.Web.Resources
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var currency = ViewBag.currency;
}


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                <h4>@Resource.eminmisin @*&nbsp;@Resource.sil : @Model.VoucherNo*@ </h4>
                <hr />
                <dl class="dl-horizontal">
                   
                    <dt>
                        @Html.DisplayNameFor(model => model.BookingDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BookingDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CheckIn)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CheckIn)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CheckOut)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CheckOut)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Surname)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Surname)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Birthday)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Birthday)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Agenta)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Agenta)
                    </dd>   

                  

                    <dt>
                        @Html.DisplayNameFor(model => model.GuestNote)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.GuestNote)
                    </dd>

                    <dt>
                        <span>@Resource.bonusTutarRezDetay</span>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Amount)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CurrencyId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => currency)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Person)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Person)
                    </dd>
                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <a class="btn bg-teal" href="@Url.Action("Index","Reservations")">
                          @Resource.rezervasyonlar
                        </a>
                        <button type="submit" class="btn bg-deep-orange">
                          @Resource.sil
                        </button>
                    </div>
                }
                </div>
            </div>
        </div>
    </div>
                  
                

ReiseBuro.Web/Views/Reservations/Details.cshtml
@model ReiseBuro.Entities.Models.Reservation
@using ReiseBuro.Web.Resources
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var currency = (IEnumerable<ReiseBuro.Entities.Models.Currency>)ViewBag.currency;
    var deservedAmount = ViewBag.DeservedAmount;
}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                <h4>@Resource.detay : @Model.VoucherNo</h4>
                <hr />
                <dl class="dl-horizontal">
                
                    <dt>
                        @Html.DisplayNameFor(model => model.BookingDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BookingDate)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CheckIn)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CheckIn)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CheckOut)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CheckOut)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Surname)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Surname)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Birthday)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Birthday)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Agenta)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Agenta)
                    </dd>


                    <dt>
                        @Html.DisplayNameFor(model => model.GuestNote)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.GuestNote)
                    </dd>

                    <dt>
                        <span>@Resource.bonusTutarRezDetay</span>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Amount)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CurrencyId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model =>currency.FirstOrDefault(f=>f.Id== model.CurrencyId).Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Person)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Person)
                    </dd>
                </dl>
                <div class="form-actions no-color">
                    <a class="btn bg-teal" href="@Url.Action("Index","Reservations")">
                        @Resource.rezervasyonlar
                    </a>
                    <a class="btn bg-teal" href="@Url.Action("Edit","Reservations", new { id = @Model.Id })">
                        @Resource.duzenle
                    </a>
                  
                </div>
               
            </div>
        </div>
    </div>
</div>
         