ReiseBuro.Web/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReiseBuro.Web.Models
{
    public class UserViewModel
    {

        [Required(ErrorMessageResourceType = typeof(Resources.Resource),
                ErrorMessageResourceName = "zorunluAlanlariDoldurunuz")]
        [Display(Name ="Kullanıcı Adı")]
        public string UserName { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources.Resource),
            ErrorMessageResourceName = "zorunluAlanlariDoldurunuz")]
        [DataType(DataType.Password)]
        [Display(Name ="Şifre")]
        public string Password { get; set; }
    }
}

ReiseBuro.Web/Controllers/UserActionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReiseBuro.Entities.Models;
using ReiseBuro.Web.Models;
using ReiseBuro.Repository.IRepository;
using ReiseBuro.Web.Authentication;
using ReiseBuro.Web.Helper;
using System.Configuration;

namespace ReiseBuro.Web.Controllers
{

    public class UserActionsController : Controller
    {
        private readonly IUserActionRepository _userActionRepository;
        private readonly IResStateRepository _resStateRepository;
        private readonly IUserRepository _userRepository;
        private readonly IReservationRepository _resRepository;

        private readonly string CancelStatus = ConfigurationManager.AppSettings["Cancel"].ToString();
        private readonly string ConfirmStatus = ConfigurationManager.AppSettings["Confirm"].ToString();
        private readonly string InsideStatus = ConfigurationManager.AppSettings["Inside"].ToString();
        private readonly string FirstConfirm = ConfigurationManager.AppSettings["TempConfirm"].ToString();
        private readonly string PaymentStatus = ConfigurationManager.AppSettings["Payment"].ToString();

        public UserActionsController(IUserActionRepository userActionRepository, IResStateRepository resStateRepository, IUserRepository userRepository, IReservationRepository resRepository)
        {
            this._userActionRepository = userActionRepository;
            this._resStateRepository = resStateRepository;
            this._userRepository = userRepository;
            this._resRepository = resRepository;
        }

        // GET: UserActions
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            var userActions = _userActionRepository.GetAll();
            ViewBag.Res = _resRepository.GetAll();
            ViewBag.states = SelectListItemHelper.GetDisplayResStatus();/*_resStateRepository.GetAll();*/
            ViewBag.user = _userRepository.GetAll();
            return View(userActions.ToList());
        }

        [ReiseAuthorize(Roles = "Kullanici")]
        public ActionResult Actions()
        {
            ViewBag.users = _userRepository.GetAll();
            ViewBag.states = SelectListItemHelper.GetDisplayResStatus();
            //ViewBag.states = _resStateRepository.GetAll();
            ViewBag.reservations = _resRepository.GetAll();
            return View(_userActionRepository.GetAll().Where(f => f.UserId == UserInfoHelper.GetUserid()));
        }

        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult UserAction(int id)  
        {
           ViewBag.Username = _userRepository.Get(id).UserName;
            ViewBag.states = SelectListItemHelper.GetDisplayResStatus();
            return View(_userActionRepository.GetAll().Where(f => f.UserId == id));
        }

        // GET: UserActions/Details/5
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAction userAction = _userActionRepository.Get(id);
            if (userAction == null)
            {
                return HttpNotFound();
            }
            return View(userAction);
        }


        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Create(int? id)
        {
            var user = _userRepository.Get(id);
            if(user==null)
            {
                return HttpNotFound();
            }
            user.Password = "";
            ViewBag.user = user;         
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Create(UserAction userAction)
        {
            if (ModelState.IsValid)
            {
                userAction.ActionDate = DateTime.Now;
                if (userAction.ResId == null)
                {
                    userAction.ActionState = PaymentStatus;
                }
                _userActionRepository.Insert(userAction);
                TempData["message"] = "İşlem Başarılı.";
                return RedirectToAction("UserAction", new { id=userAction.UserId });
            }
            ViewBag.user = _userRepository.Get(userAction.UserId);
            return View(userAction);
        }

        // GET: UserActions/Edit/5
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAction userAction = _userActionRepository.Get(id);
            if (userAction == null)
            {
                return HttpNotFound();
            }
            ViewBag.Dictionary = SelectListItemHelper.DictionaryList();
            ViewBag.Users = SelectListItemHelper.GetUsersKeyValue();
            return View(userAction);
        }

        [ReiseAuthorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserAction userAction)
        {
            if (ModelState.IsValid)
            {
                _userActionRepository.Update(userAction);
                return RedirectToAction("Index");
            }
            ViewBag.Dictionary = SelectListItemHelper.DictionaryList();
            ViewBag.Users = SelectListItemHelper.GetUsersKeyValue();
            return View(userAction);
        }

        // GET: UserActions/Delete/5
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAction userAction = _userActionRepository.Get(id);
            if (userAction == null)
            {
                return HttpNotFound();
            }
            ViewBag.Username = _userRepository.Get(userAction.UserId).UserName;
            //ViewBag.Voucher = _resRepository.Get(userAction.ResId).VoucherNo;
            return View(userAction);
        }

        // POST: UserActions/Delete/5
        [ReiseAuthorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserAction userAction = _userActionRepository.Get(id);
            _userActionRepository.Delete(userAction);
            TempData["message"] = "Hareket başarıyla silindi.";
            return RedirectToAction("UserAction", new { id = userAction.UserId });
        }

        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Cancel(int? id)
        {
            if (id == null)
                TempData["error"] = "İşlem gerçekleştirilemiyor.";

            try
            {
                var action = _userActionRepository.Get(id);
                action.BalanceReceivable = decimal.Zero;
                action.BalanceDue = decimal.Zero;

                action.ActionState = CancelStatus;
                _userActionRepository.Update(action);

                var res = _resRepository.Get(action.ResId);
                res.Amount = decimal.Zero;
                _resRepository.Update(res);

                TempData["message"] = "İşlem Başarılı";
            }
            catch (Exception ex)
            {
                TempData["error"] = "Bir Hata Oluştu. " + ex.Message;
            }

            return RedirectToAction("Index");

        }


        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Confirm(int? id)
        {
            if (id == null)
            {
                TempData["error"] = "İşlem gerçekleştirilemiyor.";
                return RedirectToAction("Index");
            }

            try
            {
                var action = _userActionRepository.Get(id);
                if (action.DeservedAmount == decimal.Zero)
                {
                    TempData["error"] = "Hakedilen miktar sıfırdan büyük olmalıdır.";
                    return RedirectToAction("Index");
                }
                action.ActionState = ConfirmStatus;
                action.BalanceReceivable = action.DeservedAmount;
                _userActionRepository.Update(action);

                var res = _resRepository.Get(action.ResId);
                res.Amount = action.DeservedAmount;
                _resRepository.Update(res);

                TempData["message"] = "İşlem Başarılı";
            }
            catch (Exception ex)
            {
                TempData["error"] = "Bir Hata Oluştu. " + ex.Message;
            }

            return RedirectToAction("Index");

        }

        [ReiseAuthorize(Roles ="Administrator")]
        public ActionResult Inside(int? id)
        {
            if (id == null)
            {
                TempData["error"] = "İşlem gerçekleştirilemiyor.";
                return RedirectToAction("Index");
            }
            try
            {
                var action = _userActionRepository.Get(id);
                action.ActionState = InsideStatus;
                _userActionRepository.Update(action);
                TempData["message"] = "İşlem Başarılı";

            }
            catch (Exception ex)
            {
                TempData["error"] = "Bir Hata Oluştu. " + ex.Message;
            }

            return RedirectToAction("Index");
        }


        [ReiseAuthorize(Roles ="Administrator")]
        public ActionResult TempConfirm(int? id)
        {         
            try
            {
                var action = _userActionRepository.Get(id);
                action.ActionState = FirstConfirm;
                _userActionRepository.Update(action);

ReiseBuro.Web/Views/UserActions/Actions.cshtml
@model IEnumerable<ReiseBuro.Entities.Models.UserAction>
@using ReiseBuro.Web.Resources


@{
    ViewBag.Title = "Actions";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var states = (IEnumerable<ReiseBuro.Web.Models.ResStatusViewModel>)ViewBag.states;
    var summary = Model.Sum(s => s.BalanceDue) - Model.Sum(d => d.BalanceReceivable);

    var note = "";
    if (summary < 0)
    {
        note = Resource.alacak;
    }
    else if (summary > 0)
    {
        note = Resource.borc;
    }

    summary = Math.Abs(summary);
    var currency = ReiseBuro.Web.Helper.UserInfoHelper.GetUserCurrency();
    var res = (IEnumerable<ReiseBuro.Entities.Models.Reservation>)ViewBag.reservations;
    var users = (IEnumerable<ReiseBuro.Entities.Models.User>)ViewBag.users;
}

<div class="block-header">
    <h2>
        @Resource.hareketler
    </h2>
</div>
<!-- Basic Examples -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h5>
                    @Resource.ozet
                </h5>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover">
                        <thead>
                            <tr>
                                <th>@Resource.hakedilecekbonus</th>
                                <th>@Resource.bonus</th>
                                <th>@Resource.odenenbonus</th>
                                <th>@Resource.total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>@Model.Sum(s => s.DeservedAmount)</td>
                                <td>@Model.Sum(s => s.BalanceReceivable)</td>
                                <td>@Model.Sum(s => s.BalanceDue)</td>
                                <td>@summary @currency</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="header">
                <h5>
                    @Resource.bonusTablosuCaption
                </h5>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.ActionDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ResId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.BalanceDue)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.BalanceReceivable)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ActionState)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DeservedAmount)
                                </th>
                                <th>
                                    @Resource.rezervasyonuYapanKisi
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ActionDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => res.FirstOrDefault(i => i.Id == item.ResId).VoucherNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.BalanceDue)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.BalanceReceivable)
                                    </td>
                                    <td>
                                        @if (!string.IsNullOrEmpty(item.ActionState))
                                        {
                                            if (string.IsNullOrEmpty(states.FirstOrDefault(f => f.ConfirmCode == item.ActionState).DisplayName))
                                            {
                                                <span>@Html.DisplayFor(modelItem => states.FirstOrDefault(f => f.ConfirmCode == item.ActionState).ConfirmState)</span>
                                            }
                                            else
                                            {
                                                <span>@Html.DisplayFor(modelItem => states.FirstOrDefault(f => f.ConfirmCode == item.ActionState).DisplayName)</span>
                                            }
                                        }
                                        @*@Html.DisplayFor(modelItem => states.FirstOrDefault(f => f.ConfirmCode == item.ActionState).ConfirmState)*@
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DeservedAmount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => users.FirstOrDefault(s => s.Id == res.FirstOrDefault(f => f.Id == item.ResId).UserId).UserName)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <!-- JQuery DataTable Css -->
    <link href="~/assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

}

@section Scripts{
    <!-- Autosize Plugin Js -->
    <script src="~/assets/plugins/autosize/autosize.js"></script>
    <!-- Moment Plugin Js -->
    <script src="~/assets/plugins/momentjs/moment.js"></script>
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <!-- Jquery DataTable Plugin Js -->
    <script src="~/assets/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="~/assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <!-- Custom Js -->
    <script src="~/assets/js/pages/tables/jquery-datatable.js"></script>

}

ReiseBuro.Web/Views/UserActions/Create.cshtml
@model ReiseBuro.Entities.Models.UserAction
@using ReiseBuro.Web.Resources

@{
    var user = (ReiseBuro.Entities.Models.User)ViewBag.user;
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block-header">
    <h2>
        @Resource.hareketolustur
    </h2>
</div>
<!-- Basic Examples -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="row clearfix">
                        <div class="col-md-4">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group form-float">
                                @*<label for="UserId" class="form-label">@Resource.kullanicisecin</label>*@
                                <div class="form-line">
                                    <input type="text" class="form-control" value="@user.UserName" readonly="readonly" />                                  
                                    <input type="hidden" name="UserId" id="UserId" value="@user.Id" />
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <label for="BalanceDue" class="form-label">@Resource.odenenbonus</label>
                                <div class="form-line">
                                    @Html.EditorFor(model => model.BalanceDue, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.BalanceDue, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            @*<div class="form-group form-float">
                                    <label for="BalanceDue" class="form-label">Dictionary</label>
                                    <div class="form-line">
                                        @Html.DropDownListFor(model => model.ActionState,new SelectList(ViewBag.Dictionary,"Value","Key"),Resource.seciniz, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.BalanceDue, "", new { @class = "text-danger" })
                                    </div>
                                </div>*@
                            <div class="form-actions">
                                <div class="col-md-offset-2 col-md-10">
                                    @Html.ActionLink(Resource.listeyedon, "Index", new { }, new { @class = "btn bg-grey" })
                                    <input type="submit" value="@Resource.olustur" class="btn bg-teal" />
                                </div>
                            </div>
                        </div>
                    </div>
                }



            </div>
        </div>
    </div>
</div>

ReiseBuro.Web/Views/UserActions/Delete.cshtml
@model ReiseBuro.Entities.Models.UserAction
@using ReiseBuro.Web.Resources
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var username = ViewBag.Username;
}


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                <h4>@Resource.eminmisin</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.UserId)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => username)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ActionDate)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ActionDate)
                    </dd>                 

                    <dt>
                        @Html.DisplayNameFor(model => model.BalanceDue)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BalanceDue)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.BalanceReceivable)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BalanceReceivable)
                    </dd>                 

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="@Resource.sil" class="btn btn-default" /> |
                        @Html.ActionLink(Resource.iptal, "UserAction", new { }, new { @class="btn-sm bg-teal" })
                    </div>
                }
            </div>
        </div>
    </div>
</div>

ReiseBuro.Web/Views/UserActions/Index.cshtml
@model IEnumerable<ReiseBuro.Entities.Models.UserAction>
@using ReiseBuro.Web.Resources

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var states = (IEnumerable<ReiseBuro.Web.Models.ResStatusViewModel>)ViewBag.states;
    var users = (IEnumerable<ReiseBuro.Entities.Models.User>)ViewBag.user;
    var res = (IEnumerable<ReiseBuro.Entities.Models.Reservation>)ViewBag.Res;
}

<div class="block-header">
    <h2>
        @Resource.hareketler
    </h2>
</div>
<!-- Basic Examples -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h5>
                    @Resource.hareketlercaption
                </h5>
                <h5 class="error-message">@TempData["error"] </h5>
                <h5 class="text-info">@TempData["message"]</h5>
            </div>
            <div class="body">

                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                        <thead>
                            <tr>

                                <th>
                                    @Html.DisplayNameFor(model => model.ActionDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.UserId)
                                </th>
                                <th>
                                    @ReiseBuro.Entities.Resources.Resource.checkout
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ResId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.BalanceDue)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.BalanceReceivable)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ActionState)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DeservedAmount)
                                </th>
                                <th>
                                    @Resource.islemler
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
            {
                                <tr>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.ActionDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => users.FirstOrDefault(f => f.Id == item.UserId).UserName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => res.FirstOrDefault(f => f.Id == item.ResId).CheckOut)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => res.FirstOrDefault(i => i.Id == item.ResId).VoucherNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.BalanceDue)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.BalanceReceivable)
                                    </td>
                                    <td>
                                        @if (!string.IsNullOrEmpty(item.ActionState))
                                        {
                                            if (string.IsNullOrEmpty(states.FirstOrDefault(f => f.ConfirmCode == item.ActionState).DisplayName))
                                            {
                                                <span>@Html.DisplayFor(modelItem => states.FirstOrDefault(f => f.ConfirmCode == item.ActionState).ConfirmState)</span>

                                            }
                                            else
                                            {
                                                <span>@Html.DisplayFor(modelItem => states.FirstOrDefault(f => f.ConfirmCode == item.ActionState).DisplayName)</span>
                                            }

                                        }

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DeservedAmount)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("TempConfirm","UserActions", new { id=item.Id })" class="btn bg-grey btn-sm">@Resource.goruldu</a>
                                        <a href="@Url.Action("Inside","UserActions", new { id=item.Id })" class="btn bg-deep-purple btn-sm">@Resource.icerde</a>
                                        <a href="@Url.Action("Confirm","UserActions", new { id=item.Id })" class="btn bg-teal btn-sm">@Resource.onay</a>
                                        <a href="@Url.Action("Cancel","UserActions", new { id=item.Id })" class="btn bg-deep-orange btn-sm">@Resource.iptal</a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
                <br />

            </div>
        </div>

    </div>
</div>


@section Styles{
    <!-- JQuery DataTable Css -->
    <link href="~/assets/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet">

}

@section Scripts{
    <!-- Autosize Plugin Js -->
    <script src="~/assets/plugins/autosize/autosize.js"></script>
    <!-- Moment Plugin Js -->
    <script src="~/assets/plugins/momentjs/moment.js"></script>
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <!-- Jquery DataTable Plugin Js -->
    <script src="~/assets/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="~/assets/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>
    <!-- Custom Js -->
    <script src="~/assets/js/pages/tables/jquery-datatable.js"></script>


}