ReiseBuro.Web/Controllers/CampaignsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReiseBuro.Entities.Models;
using ReiseBuro.Web.Models;
using ReiseBuro.Repository.IRepository;
using ReiseBuro.Web.Authentication;
using ReiseBuro.Web.Helper;
using Itenso.TimePeriod;

namespace ReiseBuro.Web.Controllers
{
    [ReiseAuthorize(Roles = "Administrator,Kullanici")]
    public class CampaignsController : Controller
    {
        private readonly ICampaignRepository _campaignRepository;
        private readonly ICountryRepository _countryRepoistory;
        private readonly ICurrencyRepository _currencyRepoistory;

        public CampaignsController(ICampaignRepository campaignRepository, ICountryRepository countryRepository, ICurrencyRepository currencyRepoistory)
        {
            this._campaignRepository = campaignRepository;
            this._countryRepoistory = countryRepository;
            this._currencyRepoistory = currencyRepoistory;
        }

        // GET: Campaigns
        public ActionResult Index(string countryCode)
        {
            var countries = _countryRepoistory.GetAll();
            var currency = _currencyRepoistory.GetAll();
            ViewBag.Countries = countries;

            Dictionary<string, string> currencies = new Dictionary<string, string>();
            foreach (var item in countries)
            {
                currencies.Add(item.Code, currency.FirstOrDefault(f => f.Id == item.CurrencyId).Xml);
            }
            ViewBag.CurrencyDict = currencies;
            var user = (User)Session["user"];
            IEnumerable<dynamic> CampainsWithRange=null;            
            
            if (UserInfoHelper.UserRole() == "Administrator")
            {
                if (string.IsNullOrEmpty(countryCode))
                    CampainsWithRange = _campaignRepository.GetGroupedCampaigns(user.CountryCode);
                else
                    CampainsWithRange = _campaignRepository.GetGroupedCampaigns(countryCode);           

                ViewBag.campaignsOrdered = CampainsWithRange;
                ViewBag.CountrySelectlist = Helper.SelectListItemHelper.GetCountryKeyValue();
                return View(_campaignRepository.GetAll().ToList());
            }

            else
            {
                CampainsWithRange = _campaignRepository.GetGroupedCampaigns(user.CountryCode);
                ViewBag.campaignsOrdered = CampainsWithRange;
                var users = (User)Session["user"];
                return View(_campaignRepository.GetAll().Where(i => i.CountryCode == users.CountryCode));
            }
        }


        // GET: Campaigns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = _campaignRepository.Get(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            ViewBag.Country = _countryRepoistory.GetByCountryCode(campaign.CountryCode).Name;
            return View(campaign);
        }

        // GET: Campaigns/Create
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            ViewBag.Countries = GetCountryKeyValue();
            return View();
        }

        private List<SelectListItem> GetCountryKeyValue()
        {
            var items = new List<SelectListItem>();
            var countries = _countryRepoistory.GetAll();
            foreach (var country in countries)
            {
                items.Add(new SelectListItem
                {
                    Text = country.Name,
                    Value = country.Code
                });
            }
            return items;
        }

        // POST: Campaigns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [ReiseAuthorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IsActive,BookingBegin,BookingEnd,CheckIn,CheckOut,CountryCode,Bonus,MinNight,CampaignCode")] Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                var oldCampaigns = _campaignRepository.GetAll().Where(f => f.BookingBegin == campaign.BookingBegin &&
                                                                      f.BookingEnd == campaign.BookingEnd &&
                                                                      f.CheckIn == campaign.CheckIn &&
                                                                      f.CheckOut == campaign.CheckOut &&
                                                                      f.CountryCode == campaign.CountryCode);

                if (oldCampaigns != null)
                {
                    foreach (var item in oldCampaigns)
                    {
                        item.IsActive = false;
                        _campaignRepository.Update(item);
                    }
                }

                _campaignRepository.Insert(campaign);
                return RedirectToAction("Index");
            }
            ViewBag.Countries = GetCountryKeyValue();
            return View(campaign);
        }

        // GET: Campaigns/Edit/5
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = _campaignRepository.Get(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            ViewBag.CountryList = GetCountryKeyValue();
            return View(campaign);
        }

        // POST: Campaigns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [ReiseAuthorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IsActive,BookingBegin,BookingEnd,CheckIn,CheckOut,CountryCode,Bonus,MinNight,CampaignCode")] Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                _campaignRepository.Update(campaign);
                return RedirectToAction("Index");
            }
            return View(campaign);
        }

        // GET: Campaigns/Delete/5
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Campaign campaign = _campaignRepository.Get(id);
            if (campaign == null)
            {
                return HttpNotFound();
            }
            ViewBag.Country = _countryRepoistory.GetByCountryCode(campaign.CountryCode).Name;
            return View(campaign);
        }

        // POST: Campaigns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ReiseAuthorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(int id)
        {
            Campaign campaign = _campaignRepository.Get(id);
            _campaignRepository.Delete(campaign);
            return RedirectToAction("Index");
        }


    }
}

ReiseBuro.Web/Controllers/DictionariesController.cs
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReiseBuro.Entities.Models;
using ReiseBuro.Web.Models;
using ReiseBuro.Repository.IRepository;
using ReiseBuro.Web.Authentication;

namespace ReiseBuro.Web.Controllers
{
    [ReiseAuthorize(Roles ="Administrator")]
    public class DictionariesController : Controller
    {
        private readonly IDictionaryRepository _dictionaryRepository;

        public DictionariesController(IDictionaryRepository dictionaryRepository)
        {
            this._dictionaryRepository = dictionaryRepository;
        }

        // GET: Dictionaries
        public ActionResult Index()
        {
            return View(_dictionaryRepository.GetAll());
        }

        // GET: Dictionaries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dictionary dictionary = _dictionaryRepository.Get(id);
            if (dictionary == null)
            {
                return HttpNotFound();
            }
            return View(dictionary);
        }

        // GET: Dictionaries/Create
        public ActionResult Create()
        {
            ViewBag.culture = Helper.SelectListItemHelper.CultureKeyValue();
            return View();
        }

        // POST: Dictionaries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dictionary dictionary)
        {
            if (ModelState.IsValid)
            {
                var dic = _dictionaryRepository.GetAll().Where(f => f.D_Key == dictionary.D_Key && f.D_Culture == dictionary.D_Culture);
                if(dic.Count() >0)
                {
                    ViewBag.culture = Helper.SelectListItemHelper.CultureKeyValue();
                    TempData["error"] = "Dil ve anahtar kelime aynı olan başka bir kayıt var, ikinciyi giremezsiniz. Mevcut kaydı düzenleyin veya başka bir anahtar kelime yaratın.";
                    return View(dictionary);
                }
                _dictionaryRepository.Insert(dictionary);
                return RedirectToAction("Index");
            }

            return View(dictionary);
        }

        // GET: Dictionaries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dictionary dictionary = _dictionaryRepository.Get(id);
            if (dictionary == null)
            {
                return HttpNotFound();
            }
            return View(dictionary);
        }

        // POST: Dictionaries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Dictionary dictionary)
        {
            if (ModelState.IsValid)
            {
                _dictionaryRepository.Update(dictionary);
                return RedirectToAction("Index");
            }
            return View(dictionary);
        }

        // GET: Dictionaries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dictionary dictionary = _dictionaryRepository.Get(id);
            if (dictionary == null)
            {
                return HttpNotFound();
            }
            return View(dictionary);
        }

        // POST: Dictionaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dictionary dictionary = _dictionaryRepository.Get(id);
            _dictionaryRepository.Delete(dictionary);
            return RedirectToAction("Index");
        }

    }
}

ReiseBuro.Web/Controllers/LanguagesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ReiseBuro.Entities.Models;
using ReiseBuro.Repository.IRepository;

namespace ReiseBuro.Web.Controllers
{
    public class LanguagesController : Controller
    {
        private readonly ILanguageRepository _langRepsitory;
        private readonly ICountryRepository _countryRepsitory;

        public LanguagesController(ILanguageRepository langRepository, ICountryRepository countryRepsitory)
        {
            this._langRepsitory = langRepository;
            this._countryRepsitory = countryRepsitory;
        }

        // GET: Languages
        public ActionResult Index()
        {
            return View(_langRepsitory.GetAll().ToList());
        }

        // GET: Languages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Language language = _langRepsitory.Get(id);
            if (language == null)
            {
                return HttpNotFound();
            }
            return View(language);
        }

        // GET: Languages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Languages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DisplayName,Culture")] Language language)
        {
            if (ModelState.IsValid)
            {
                _langRepsitory.Insert(language);
                return RedirectToAction("Index");
            }

            return View(language);
        }

        // GET: Languages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Language language = _langRepsitory.Get(id);
            if (language == null)
            {
                return HttpNotFound();
            }
            return View(language);
        }

        // POST: Languages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DisplayName,Culture")] Language language)
        {
            if (ModelState.IsValid)
            {
                _langRepsitory.Update(language);
                return RedirectToAction("Index");
            }
            return View(language);
        }

        // GET: Languages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Language language = _langRepsitory.Get(id);
            if (language == null)
            {
                return HttpNotFound();
            }
            return View(language);
        }

        // POST: Languages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Language language = _langRepsitory.Get(id);
            _langRepsitory.Delete(language);
            return RedirectToAction("Index");
        }


    }
}

ReiseBuro.Web/Views/Shared/_Layout.cshtml
@using ReiseBuro.Web.Helper;
@using ReiseBuro.Web.Resources
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>RMOS YAZILIM | ReiseBuro</title>
    <!-- Favicon-->
    @*<link rel="icon" href="../../favicon.ico" type="image/x-icon">*@
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Core Css -->
    <link href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Waves Effect Css -->
    <link href="~/assets/plugins/node-waves/waves.min.css" rel="stylesheet" />
    <!-- Animation Css -->
    <link href="~/assets/plugins/animate-css/animate.min.css" rel="stylesheet" />
    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="~/assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet" />
    <!-- Wait Me Css -->
    <link href="~/assets/plugins/waitme/waitMe.css" rel="stylesheet" />
    <!-- Bootstrap Select Css -->
    <link href="~/assets/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="~/assets/css/style.min.css" rel="stylesheet">
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="~/assets/css/themes/all-themes.min.css" rel="stylesheet" />
   
    @RenderSection("Styles", false);

    <style>
        .user-info {
            background: url("/assets/images/user-img-background.jpg") no-repeat no-repeat !important;
        }

        .error-message {
            color: red;
        }

        .btn:not(.btn-link):not(.btn-circle) span {
            top: 0px;
            margin-left: 10px;
        }

        .language-dropdown {
            margin-top: 20px;
        }

       dt {
            width:15% !important;
            margin-right: 10px !important;
        }
    </style>
</head>
@{
    var isAdmin = UserInfoHelper.UserRole() == "Administrator" ? true : false;
    var culture = ReiseBuro.Web.Helper.SelectListItemHelper.CultureKeyValue();
    var currentCulture = System.Globalization.CultureInfo.CurrentCulture.TwoLetterISOLanguageName;
}
<body class="theme-teal">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>@Resource.lutfenbekleyin...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->
    <div class="search-bar">
        <div class="search-icon">
            <i class="material-icons">search</i>
        </div>
        <input type="text" placeholder="Arayın...">
        <div class="close-search">
            <i class="material-icons">close</i>
        </div>
    </div>
    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="#">ReiseBuro</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    @Html.DropDownList("SelectLanguage", new SelectList(culture, "Value", "Text"), new { @class = "form-control language-dropdown" })                   
               
                 </ul>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
      
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- User Info -->
            <div class="user-info">
                <div class="image">
                    <img src="~/assets/images/user.png" width="48" height="48" alt="User" />
                </div>
                <div class="info-container">
                    <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@UserInfoHelper.UserFullname()</div>
                    <div class="email">@UserInfoHelper.UserMailAddress()</div>
                    <div class="btn-group user-helper-dropdown">
                        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="@Url.Action("Profil","Account")"><i class="material-icons">person</i>@Resource.profilim</a></li>
                            <li role="seperator" class="divider"></li>
                            @if (isAdmin)
                            {
                                <li><a href="@Url.Action("Index","Manage")"><i class="material-icons">group</i>@Resource.kullanicionayla</a></li>
                            }
                            <li>
                                <a href="@Url.Action("LogOut","Account")"><i class="material-icons">input</i>@Resource.cikisyap</a>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- #User Info -->
            <!-- Menu -->
            <div class="menu">
                <ul class="list">


                    @if (isAdmin)
                    {
                        <li class="active" style="display:block;"></li>
                        <li class="">
                            <a href="@Url.Action("Index","Reservations")">
                                <i class="material-icons">assignment</i>
                                <span>@Resource.rezervasyonlar</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","UserActions")">
                                <i class="material-icons">favorite</i>
                                <span>@Resource.hareketler</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Summary","UserActions")">
                                <i class="material-icons">favorite</i>
                                <span>@Resource.ozethareketler</span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" class="menu-toggle">
                                <i class="material-icons">layers</i>
                                <span>@Resource.parametreler</span>
                            </a>
                            <ul class="ml-menu">
                                <li>
                                    <a href="@Url.Action("Mail","Parameters")">@Resource.mailparametreleri</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Country","Parameters")">@Resource.ulkeler</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Currency","Parameters")">@Resource.kurlar</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("ResState","Parameters")">@Resource.rezdurumlari</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index","Languages")">@Resource.dilparametreleri</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Images","Home")">Kullanıcı Kılavuz Fotoğrafları</a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="@Url.Action("Index","Dictionaries")">
                                <i class="material-icons">text_fields</i>
                                <span>@Resource.sozlukparametreleri</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Campaigns")">
                                <i class="material-icons">shopping_cart</i>
                                <span>@Resource.kampanyalar</span>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="active" style="display:block;"></li>
                        <li>
                            <a href="@Url.Action("Create","Reservations")">
                                <i class="material-icons">home</i>
                                <span>@Resource.rezolustur</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index","Reservations")">
                                <i class="material-icons">assignment</i>
                                <span>@Resource.rezervasyonlar</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Actions","UserActions")">
                                <i class="material-icons">favorite</i>
                                <span>@Resource.hareketler</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Campaigns")">
                                <i class="material-icons">shopping_cart</i>
                                <span>@Resource.kampanyalar</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Contact","Home")">
                                <i class="material-icons">phone</i>
                                <span>@Resource.iletisim</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Info","Home")">
                                <i class="material-icons">help_outline</i>
                                <span>@Resource.nasilKullanilacak</span>
                            </a>
                        </li>
                    }

                

                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; 2017 <a href="javascript:void(0);"></a>
                </div>

            </div>
            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->

    </section>
    <section class="content">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </section>
 <input type="hidden" id="CurrentLanguage" name="CurrentLanguage" value="@currentCulture" />
    <!-- Jquery Core Js -->
    <script src="~/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- Select Plugin Js -->
    <script src="~/assets/plugins/bootstrap-select/js/bootstrap-select.min.js"></script>
    <!-- Slimscroll Plugin Js -->
    <script src="~/assets/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <script src="~/assets/plugins/bootstrap-select/i18n/defaults-tr_TR.min.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="~/assets/plugins/node-waves/waves.min.js"></script>
    <!-- Autosize Plugin Js -->
    <script src="~/assets/plugins/autosize/autosize.js"></script>
    <!-- Moment Plugin Js -->
    @*<script src="~/assets/plugins/momentjs/moment.js"></script>*@

    <!-- Custom Js -->
    @*<script src="~/assets/js/admin.js"></script>*@
    <script src="~/assets/js/pages/forms/basic-form-elements.js"></script>

    <!-- Demo Js -->
    <script src="~/assets/js/demo.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment-with-locales.min.js"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script src="~/assets/js/admin.js"></script>
    <script>

        $('#SelectLanguage').val($('#CurrentLanguage').val());

        $(document).ready(function () {

            $('.language-dropdown').on('change', function () {
                var data = this.selectedOptions[0].value;
                $.post("/Home/SelectLanguage", { data: data })
                          .done(function () {
                              location.reload();
                              //$('.language-dropdown select').val(data);
                          })
                    .fail(function () {
                        alert("error");
                    });
            });
        });

    </script>
    @RenderSection("Scripts", false);
</body>
</html>