ReiseBuro.Web/Models/MailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReiseBuro.Web.Models
{
    public class MailViewModel
    {
        [Required]
        public string Content { get; set; }

        public string Subject { get; set; }
        public string MailAddress { get; set; }
    }
}

ReiseBuro.Web/Controllers/ParametersController.cs
using ReiseBuro.Entities.Models;
using ReiseBuro.Repository.IRepository;
using ReiseBuro.Web.Authentication;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ReiseBuro.Web.Controllers
{
    [ReiseAuthorize(Roles = "Administrator")]
    public class ParametersController : Controller
    {
        private readonly IPrmMailRepository _prmMailRepository;
        private readonly ICountryRepository _countryRepository;
        private readonly ICurrencyRepository _currencyRepository;
        private readonly IResStateRepository _resStateRepository;
        private readonly IFloorRepository _floorRepository;
        private readonly ILandscapeRepository _landscapeRepository;
        private readonly ILanguageRepository _langRepository;

        public ParametersController(IPrmMailRepository prmMailRepository, ICountryRepository countryRepository, ICurrencyRepository currencyRepository, IResStateRepository resStateRepository, IFloorRepository floorRepository, ILandscapeRepository landscapeRepository, ILanguageRepository langRepository)
        {
            this._prmMailRepository = prmMailRepository;
            this._countryRepository = countryRepository;
            this._currencyRepository = currencyRepository;
            this._resStateRepository = resStateRepository;
            this._floorRepository = floorRepository;
            this._landscapeRepository = landscapeRepository;
            this._langRepository = langRepository;
        }

        // GET: Parameters

        #region Mails
        public ActionResult Mail()
        {
            return View(_prmMailRepository.GetAll());
        }

        [HttpGet]
        public ActionResult CreateMail()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateMail(Param_Mail mail, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    byte[] imgByte = null;
                    imgByte = new byte[image.ContentLength];
                    image.InputStream.Read(imgByte, 0, image.ContentLength);
                    mail.ContactPhoto = Convert.ToBase64String(imgByte);
                }

                _prmMailRepository.Insert(mail);
                return RedirectToAction("Mail");
            }
            return View(mail);
        }

        [HttpGet]
        public ActionResult EditMail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var mail = _prmMailRepository.Get(id);
            if (mail == null)
            {
                return HttpNotFound();
            }
            ViewBag.Dictionary = Helper.SelectListItemHelper.DictionaryList();
            return View(mail);
        }

        [HttpPost]     
        public ActionResult EditMail(Param_Mail mail, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {

                if (image != null)
                {
                    byte[] imgByte = null;
                    imgByte = new byte[image.ContentLength];
                    image.InputStream.Read(imgByte, 0, image.ContentLength);
                    mail.ContactPhoto = Convert.ToBase64String(imgByte);
                }
                else
                {
                    var tempParam = _prmMailRepository.Get(mail.Id);
                    mail.ContactPhoto = tempParam.ContactPhoto;
                }

                _prmMailRepository.Update(mail);
                return RedirectToAction("Mail");
            }
            ViewBag.Dictionary = Helper.SelectListItemHelper.DictionaryList();
            return View(mail);
        }

        public JsonResult DeleteMail(int id)
        {
            try
            {
                var mail = _prmMailRepository.Get(id);
                _prmMailRepository.Delete(mail);
            }
            catch (Exception ex)
            {
                return Json(new { error = true, message = "İşlem Başarısız. " + ex.Message });
            }

            return Json(new { success = true, message = "İşlem Başarılı" });
        }

        #endregion


        #region countries
        public ActionResult Country()
        {
            ViewBag.Languages = _langRepository.GetAll();
            return View(_countryRepository.GetAll());
        }

        [HttpGet]
        public ActionResult CreateCountry()
        {
            ViewBag.currency = GetCurrencyKeyValue();
            ViewBag.language = Helper.SelectListItemHelper.GetLanguageKeyValue();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCountry(Country country)
        {
            if (ModelState.IsValid)
            {
                if(_countryRepository.GetAll().Any(f => f.Code == country.Code))
                {
                    TempData["error"] = "Ülke Kodu Daha Önce Tanımlanmış.Litfen Başka Bir Kod Girin.";
                    ViewBag.currency = GetCurrencyKeyValue();
                    return View(country);
                }
                _countryRepository.Insert(country);
                return RedirectToAction("Country");
            }
            ViewBag.currency = GetCurrencyKeyValue();
            return View(country);
        }

        [HttpGet]
        public ActionResult EditCountry(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            ViewBag.language = Helper.SelectListItemHelper.GetLanguageKeyValue();
            ViewBag.currency = GetCurrencyKeyValue();
            return View(_countryRepository.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCountry(Country country)
        {
            if (ModelState.IsValid)
            {
                _countryRepository.Update(country);
                return RedirectToAction("Country");
            }
            ViewBag.language = Helper.SelectListItemHelper.GetLanguageKeyValue();
            ViewBag.currency = GetCurrencyKeyValue();
            return View(country);
        }

        public ActionResult DeleteCountry(int? id)
        {
            if (id != null)
            {
                var obj = _countryRepository.Get(id);
                _countryRepository.Delete(obj);
                return RedirectToAction("Country");
            }
            TempData["error"] = "Bir hata oluştu.";
            return RedirectToAction("Country");
        }
        #endregion


        #region currencies
        public ActionResult Currency()
        {
            return View(_currencyRepository.GetAll());
        }

        [HttpGet]
        public ActionResult CreateCurrency()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCurrency(Currency currency)
        {
            if (ModelState.IsValid)
            {
                _currencyRepository.Insert(currency);
                return RedirectToAction("Currency");
            }

            return View(currency);
        }

        [HttpGet]
        public ActionResult EditCurrency(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            return View(_currencyRepository.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCurrency(Param_Mail mail)
        {
            return View();
        }


        public ActionResult DeleteCurrency(int id)
        {
            return View();
        }
        #endregion

        #region reservation states
        public ActionResult ResState()
        {
            return View(_resStateRepository.GetAll());
        }

        [HttpGet]
        public ActionResult CreateResState()
        {
            ViewBag.Dictionary = ReiseBuro.Web.Helper.SelectListItemHelper.DictionaryList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateResState(ResState obj)
        {
            if (ModelState.IsValid)
            {
                _resStateRepository.Insert(obj);
                return RedirectToAction("ResState");
            }
            ViewBag.Dictionary = ReiseBuro.Web.Helper.SelectListItemHelper.DictionaryList();
            return View(obj);
        }

        [HttpGet]
        public ActionResult EditResState(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var rezstate = _resStateRepository.Get(id);
            if (rezstate == null)
            {
                return HttpNotFound();
            }
            ViewBag.Dictionary = Helper.SelectListItemHelper.DictionaryList();
            return View(rezstate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditResState(ResState obj)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Dictionary = Helper.SelectListItemHelper.DictionaryList();
                return View();

            }
            _resStateRepository.Update(obj);
            return RedirectToAction("ResState");

        }

        public ActionResult DeletResState(int? id)
        {
            if (id != null)
            {
                var obj = _countryRepository.Get(id);
                _countryRepository.Delete(obj);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { error = true }, JsonRequestBehavior.AllowGet);
        }


        #endregion


        #region Floors
        public ActionResult Floor()
        {

ReiseBuro.Web/Views/Parameters/Country.cshtml
@model IEnumerable<ReiseBuro.Entities.Models.Country>

@{
    ViewBag.Title = "Countries";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var langs = (IEnumerable<ReiseBuro.Entities.Models.Language>)ViewBag.Languages;
}

<div class="block-header">
    <h2>
        ÜLKELER
    </h2>
</div>
<!-- Basic Examples -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">

            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Code)
                                </th>
                                <th>
                                   <label for="LanguageId">Dil</label>
                                </th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Code)
                                    </td>
                                    <td>
                                        @langs.FirstOrDefault(f => f.Id == item.LanguageId).DisplayName
                                    </td>
                                    <td>
                                        @Html.ActionLink("DÜZENLE", "EditCountry", new { id = item.Id }, new { @class = "btn btn-sm bg-deep-orange" })                                        
                                        @Html.ActionLink("SİL", "DeleteCountry", new { id = item.Id }, new { @class = "btn btn-sm bg-deep-purple" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="form-actions">
                    @Html.ActionLink("Yeni Kayıt Oluştur", "CreateCountry", new { }, new { @class = "createParam btn bg-teal" })
                </div>
            </div>
        </div>
    </div>
</div>


@section Styles{

    <style>
        .createParam {
            margin: 15px 0 10px 0;
        }

        .btn-sm {
            padding: 2px 20px !important;
            margin: 5px 0 0 0;
        }
    </style>

}

@section Scripts{

    <script src="~/assets/plugins/autosize/autosize.js"></script>
}

ReiseBuro.Web/Views/Parameters/CreateCountry.cshtml
@model ReiseBuro.Entities.Models.Country

@{
    ViewBag.Title = "CreateCountry";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="block-header">
    <h2>Ülke Oluştur</h2>
</div>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="row clearfix">
                        <div class="col-md-4">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group form-float">                              
                                @Html.LabelFor(model => model.Name,"Ülke Adı", htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Code,"Ülke Kodu", htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.CurrencyId,"Kur", htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.DropDownListFor(model => model.CurrencyId, new SelectList(ViewBag.currency,"Value", "Text"), new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CurrencyId, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.LanguageId,"Dil", htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.DropDownListFor(model => model.LanguageId, new SelectList(ViewBag.language, "Value", "Text"), new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LanguageId, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-actions">
                                <div class="col-md-offset-2 col-md-10">
                                    @Html.ActionLink("Listeye Dön", "Country", new { }, new { @class = "btn bg-teal" })
                                    <input type="submit" value="OLUŞTUR" class="btn bg-deep-purple" />
                                </div>
                            </div>
                            <h4 class="error-message">@TempData["error"]</h4>
                        </div>
                    </div>
                }

             

            </div>
        </div>
    </div>
</div>



@section Styles{

}

@section Scripts{
    <!-- Autosize Plugin Js -->
    <script src="~/assets/plugins/autosize/autosize.js"></script>
    <!-- Moment Plugin Js -->
    <script src="~/assets/plugins/momentjs/moment.js"></script>
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script>


    </script>

}

ReiseBuro.Web/Views/Parameters/CreateCurrency.cshtml
@model ReiseBuro.Entities.Models.Currency

@{
    ViewBag.Title = "CreateCurrency";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block-header">
    <h2>Kur Oluştur</h2>
</div>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="row clearfix">
                        <div class="col-md-4">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Xml, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Xml, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Xml, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-actions">
                                <div class="col-md-offset-2 col-md-10">
                                    @Html.ActionLink("Listeye Dön", "Currency", new { }, new { @class="btn bg-deep-purple"})
                                    <input type="submit" value="OLUŞTUR" class="btn bg-teal" />
                                </div>
                            </div>
                        </div>
                    </div>
                }              

            </div>
        </div>
    </div>
</div>

ReiseBuro.Web/Views/Parameters/EditMail.cshtml
@model ReiseBuro.Entities.Models.Param_Mail
@using ReiseBuro.Web.Resources
@{
    ViewBag.Title = "EditMail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block-header">
    <h2>Mail Düzenle</h2>
</div>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                @using (Html.BeginForm("EditMail","Parameters", FormMethod.Post, new { @enctype="multipart/form-data"}))
                {

                    <div class="row clearfix">
                        <div class="col-md-4">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model=>model.Ssl)
                            @Html.HiddenFor(model => model.IsActive)

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.MailAddress, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.MailAddress, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MailAddress, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.DisplayMail, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.DisplayMail, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DisplayMail, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Host, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Host, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Host, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Parola, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Parola, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Parola, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Port, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Port, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Port, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <input type="checkbox" class="filled-in" id="IsSsl" name="IsSsl" />
                                <label for="IsSsl"><b>Ssl</b></label>
                                        @Html.ValidationMessageFor(model => model.Ssl, "", new { @class = "text-danger" })
                                  
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.Stmp, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.Stmp, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Stmp, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.CcList, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.CcList, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CcList, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.MailCaption, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.DropDownListFor(model => model.CaptionKeyword, new SelectList(ViewBag.Dictionary, "Value", "Text"), Resource.seciniz, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MailCaption, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.MailContent, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.DropDownListFor(model => model.MessageKeyword, new SelectList(ViewBag.Dictionary, "Value", "Text"), Resource.seciniz, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MailContent, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.ContactPosition, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.ContactPosition, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ContactPosition, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.ContactPhoto, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    <img src="data:image/png;base64, @Model.ContactPhoto" alt="Image" />
                                    <input type="file" name="image" accept="image/*">      
                                    @Html.ValidationMessageFor(model => model.ContactPhoto, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                @Html.LabelFor(model => model.ContactMessage, htmlAttributes: new { @class = "form-label" })
                                <div class="form-line">
                                    @Html.EditorFor(model => model.ContactMessage, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ContactMessage, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <input type="checkbox" class="filled-in" id="IsActiveDisplay" name="IsActiveDisplay" />
                                <label for="IsActiveDisplay"><b>Aktif mi</b></label>
                                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-actions">
                                <div class="col-md-offset-2 col-md-10">
                                    @Html.ActionLink("Listeye Dön", "Mail",new { }, new { @class="btn bg-deep-orange"})
                                    <input type="submit" value="Kaydet" class="btn bg-teal" />
                                </div>
                            </div>
                        </div>
                    </div>
                }

                <div>
                   
                </div>



            </div>
        </div>
    </div>
</div>


@section Styles{

}

@section Scripts{
    <!-- Autosize Plugin Js -->
    <script src="~/assets/plugins/autosize/autosize.js"></script>
    <!-- Moment Plugin Js -->
    <script src="~/assets/plugins/momentjs/moment.js"></script>
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script>

        $(document).ready(function () {

            if ($('#Ssl').val()) {
                $('#IsSsl').prop('checked', true)
            } else {
                $('#IsSsl').prop('checked', false)
            }

            if ($('#IsActive').val()) {
                $('#IsActiveDisplay').prop('checked', true)
            } else {
                $('#IsActiveDisplay').prop('checked', false)
            }

        });


        $('#SslDisplay').change(function () {
            var confirm = $('#SslDisplay').prop('checked');
            $('#Ssl').val(confirm);
        });

        $('#IsActiveDisplay').change(function () {
            var confirm = $('#IsActiveDisplay').prop('checked');
            $('#IsActive').val(confirm);
        });


    </script>

}